services:
  newsapp:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run start
    env_file:
      - .env.local
    volumes:
      - .:/newsapp
      - /app/node_modules
    
    